version: '3.8'
services:
  mlops-service:
    container_name: mlops-service
    image: mlops-service
    build: .
    command: make run
    volumes:
      - .:/app/services/service
    ports:
      - "3000:3000"
    networks:
      - local
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    networks:
      - local
  mlflow:
    image: ubuntu/mlflow:2.1.1_1.0-22.04
    container_name: tracker_mlflow
    restart: unless-stopped
    command: python3 -m mlflow ui --port 5000
    ports:
      - "5000:5000"
    networks:
      - local
networks:
  local:
    driver: bridge